# Step 1: Build stage
FROM node:14.16.0-alpine3.13 AS build-stage

ENV NODE_ENV="production" PORT="3000"

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

RUN  npm run build


# Step 2: Production stage
FROM nginx:1.12-alpine AS production-stage
RUN addgroup app && adduser -SG app app
USER app
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off"]
