--- # Sample run: docker-compose up --build -d
version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  frontend-tests:
    depends_on:
      - frontend
    image: vidly_frontend
    command: npm test

  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  #TODO: fix backend- tests
  # backend-tests:
  #   depends_on:
  #     - backend
  #   image: vidly_backend
  #   command: npm test

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
